name: Runners hospedados - Docker

on:
  workflow_dispatch:

jobs:
  docker:
    name: Contenerizacion con Docker y .NET
    runs-on: [self-hosted,windows]
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build src --file src/wpm-api/WisdomPetMedicine.Api/Dockerfile --tag
